### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [magufl/magufl-excusegenerator#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Buen trabajo @magufl ... ¡Felicidades!
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
- ¡Bien resuelto!
- Para seguir practicando JS, te recomiendo duplicar el repositorio y usar el método `.map` para la lógica de tu proyecto

**Comment by magufl** [comment]
Gracias!!
